//verbs list from https://eslgrammar.org/list-of-verbs/
//nouns list from https://eslgrammar.org/list-of-nouns/
//adverbs list from https://grammar.yourdictionary.com/parts-of-speech/adverbs/list-of-100-adverbs.html
//adjectives list from https://grammar.yourdictionary.com/parts-of-speech/adjectives/list-of-adjective-words.html


let verbs = ['accept', 'guess', 'achieve', 'harass', 'add', 'hate', 'admire', 'hear', 'admit', 'help', 'adopt', 'hit', 'advise', 'hope', 'agree', 'identify', 'allow', 'interrupt', 'announce', 'introduce', 'appreciate', 'irritate', 'approve', 'jump', 'argue', 'keep', 'arrive', 'kick', 'ask', 'kiss', 'assist', 'laugh', 'attack', 'learn', 'bake', 'leave', 'bathe', 'lend', 'be', 'lie', 'beat', 'like', 'become', 'listen', 'beg', 'lose', 'behave', 'love', 'bet', 'make', 'boast', 'marry', 'boil', 'measure', 'borrow', 'meet', 'breathe', 'move', 'bring', 'murder', 'build', 'obey', 'burn', 'offend', 'bury', 'offer', 'buy', 'open', 'call', 'paint', 'catch', 'pay', 'challenge', 'pick', 'change', 'play', 'cheat', 'pray', 'chew', 'print', 'choose', 'pull', 'clap', 'punch', 'clean', 'punish', 'collect', 'purchase', 'compare', 'push', 'complain', 'quit', 'confess', 'race', 'confuse', 'read', 'construct', 'relax', 'control', 'remember', 'copy', 'reply', 'count', 'retire', 'create', 'rub', 'cry', 'see', 'damage', 'select', 'dance', 'sell', 'deliver', 'send', 'destroy', 'sing', 'disagree', 'snore', 'drag', 'stand', 'drive', 'stare', 'drop', 'start', 'earn', 'stink', 'eat', 'study', 'employ', 'sweep', 'encourage', 'swim', 'enjoy', 'take', 'establish', 'talk', 'estimate', 'teach', 'exercise', 'tear', 'expand', 'tell', 'explain', 'thank', 'fear', 'travel', 'feel', 'type', 'fight', 'understand', 'find', 'use', 'fly', 'visit', 'forget', 'wait', 'forgive', 'walk', 'fry', 'want', 'gather', 'warn', 'get', 'wed', 'give', 'weep', 'glow', 'wink', 'greet', 'worry', 'grow', 'write', 'yell']

let nouns = ['actor', 'gold', 'painting', 'advertisement', 'grass', 'parrot', 'afternoon', 'greece', 'pencil', 'airport', 'guitar', 'piano', 'ambulance', 'hair', 'pillow', 'animal', 'hamburger', 'pizza', 'answer', 'helicopter', 'planet', 'apple', 'helmet', 'plastic', 'army', 'holiday', 'portugal', 'australia', 'honey', 'potato', 'balloon', 'horse', 'queen', 'banana', 'hospital', 'quill', 'battery', 'house', 'rain', 'beach', 'hydrogen', 'rainbow', 'beard', 'ice', 'raincoat', 'bed', 'insect', 'refrigerator', 'belgium', 'insurance', 'restaurant', 'boy', 'iron', 'river', 'branch', 'island', 'rocket', 'breakfast', 'jackal', 'room', 'brother', 'jelly', 'rose', 'camera', 'jewellery', 'russia', 'candle', 'jordan', 'sandwich', 'car', 'juice', 'school', 'caravan', 'kangaroo', 'scooter', 'carpet', 'king', 'shampoo', 'cartoon', 'kitchen', 'shoe', 'china', 'kite', 'soccer', 'church', 'knife', 'spoon', 'crayon', 'lamp', 'stone', 'crowd', 'lawyer', 'sugar', 'daughter', 'leather', 'sweden', 'death', 'library', 'teacher', 'denmark', 'lighter', 'telephone', 'diamond', 'lion', 'television', 'dinner', 'lizard', 'tent', 'disease', 'lock', 'thailand', 'doctor', 'london', 'tomato', 'dog', 'lunch', 'toothbrush', 'dream', 'machine', 'traffic', 'dress', 'magazine', 'train', 'easter', 'magician', 'truck', 'egg', 'manchester', 'uganda', 'eggplant', 'market', 'umbrella', 'egypt', 'match', 'van', 'elephant', 'microphone', 'vase', 'energy', 'monkey', 'vegetable', 'engine', 'morning', 'vulture', 'england', 'motorcycle', 'wall', 'evening', 'nail', 'whale', 'eye', 'napkin', 'window', 'family', 'needle', 'wire', 'finland', 'nest', 'xylophone', 'fish', 'nigeria', 'yacht', 'flag', 'night', 'yak', 'flower', 'notebook', 'zebra', 'football', 'ocean', 'zoo', 'forest', 'oil', 'garden', 'fountain', 'orange', 'gas', 'france', 'oxygen', 'girl', 'furniture', 'oyster', 'glass', 'garage', 'ghost']

let adverbs = ['boldly', 'bravely', 'brightly', 'cheerfully', 'deftly', 'devotedly', 'eagerly', 'elegantly', 'faithfully', 'fortunately', 'gleefully', 'gracefully', 'happily', 'honestly', 'innocently', 'kindly', 'merrily', 'obediently', 'perfectly', 'politely', 'powerfully', 'safely', 'victoriously', 'warmly', 'vivaciously']

let adjectives = ['lazy', 'light', 'lively', 'lonely', 'long', 'lovely', 'lucky', 'magnificent', 'misty', 'modern', 'motionless', 'muddy', 'mushy', 'mysterious', 'nasty', 'naughty', 'nervous', 'nice', 'nutty', 'obedient', 'obnoxious', 'odd', 'old-fashioned', 'open', 'outrageous', 'outstanding', 'panicky', 'perfect', 'plain', 'pleasant', 'poised', 'poor', 'powerful', 'precious', 'prickly', 'proud', 'putrid', 'puzzled', 'quaint', 'real', 'relieved', 'repulsive', 'rich', 'scary', 'selfish', 'shiny', 'shy', 'silly', 'sleepy', 'smiling', 'smoggy', 'sore', 'sparkling', 'splendid', 'spotless', 'stormy', 'strange', 'stupid', 'successful', 'super']